version: '3'

services:
 

  rclone-mount:
    image: pablokbs/rclone-mount:armhf
    restart: unless-stopped
    ports:
      - '80:80'
    cap_add:
      - SYS_ADMIN
    security_opt:
      - 'apparmor:unconfined'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - '/~.config/rclone:/config'
      - '/mnt/gdrive:/mnt/mediaefs:shared'
    logging:
      options:
        max-size: 1g
    container_name: rclone-mount
    devices:
      - /dev/fuse
    environment:
      - 'RemotePath=gdrive:'
      - 'MountCommands=--allow-other --allow-non-empty --buffer-size 256M'
      - 'ConfigName=rclone.conf'
